services:
  odoo:
    restart: unless-stopped
    ports:
      - 127.0.0.1:8069:8069
      - 127.0.0.1:8071:8071
      - 127.0.0.1:8072:8072

  postgres:
    restart: unless-stopped
    ports:
      - 127.0.0.1:5432:5432

  nginx-proxy:
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443

  letsencrypt:
    image: nginxproxy/acme-companion:2.2.8
    depends_on:
      - nginx-proxy
    restart: unless-stopped
    volumes_from:
      - nginx-proxy:rw
    volumes:
      - certs:${NGINX_CERTS}:rw
      - acme:${NGINX_ACME}
      - ${DOCKER_SOCK}:${DOCKER_SOCK}:ro
    environment:
      - DEFAULT_EMAIL
    networks:
      - internal

volumes:
  acme:
  certs:
