services:
  pgadmin:
    image: dpage/pgadmin4:${PGADMIN_TAG}
    restart: unless-stopped
    expose:
      - 80
    volumes:
      - pgadmin-data:${PGADMIN_DATA}
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
      - VIRTUAL_HOST=${PGADMIN_VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${PGADMIN_LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL
    networks:
      - internal

volumes:
  pgadmin-data:
