services:
  odoo:
    build:
      context: ./
      dockerfile: ./odoo/Dockerfile
      args:
        - ODOO_TAG
        - ODOO_RC
        - ROOT_PATH
        - GITHUB_USER
        - GITHUB_ACCESS_TOKEN
        - ENTERPRISE_ADDONS
        - THIRD_PARTY_ADDONS
        - LOG_PATH
    ports:
      - 8069:8069
      - 8071:8071
      - 8072:8072
    tty: true
    volumes:
      - odoo-data:${DATA_DIR}
      - ./odoo/extra-addons:${EXTRA_ADDONS}
      - ./odoo/custom-addons:${CUSTOM_ADDONS}
      - ./odoo/entrypoint.sh:/entrypoint.sh
    environment:
      - HOST=${DB_HOST}
      - PORT=${DB_PORT}
      - USER=${DB_USER}
      - PASSWORD=${DB_PASSWORD}
      - ODOO_TAG
      - ODOO_RC
      - THIRD_PARTY_ADDONS
      - ODOO_SESSION_REDIS
      - ODOO_SESSION_REDIS_HOST
      - ODOO_SESSION_REDIS_PORT
      - ODOO_SESSION_REDIS_PASSWORD
      - ODOO_SESSION_REDIS_URL
      - ODOO_SESSION_REDIS_PREFIX
      - ODOO_SESSION_REDIS_SENTINEL_MASTER_NAME
      - ODOO_SESSION_REDIS_SENTINEL_HOST
      - ODOO_SESSION_REDIS_SENTINEL_PORT
      - ODOO_SESSION_REDIS_EXPIRATION
      - ODOO_SESSION_REDIS_EXPIRATION_ANONYMOUS
      - AWS_HOST
      - AWS_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_BUCKETNAME
    networks:
      - internal

  nginx:
    image: nginx:${NGINX_TAG}
    depends_on:
      - odoo
    restart: unless-stopped
    tty: true
    expose:
      - 80/tcp
    volumes:
      - ./nginx/nginx.conf:${NGINX_CONF}
      - ./nginx/default.conf:${NGINX_DEFAULT_CONF}
    environment:
      - VIRTUAL_HOST
      # - LETSENCRYPT_HOST
      # - LETSENCRYPT_EMAIL
      - CORS_ALLOWED_DOMAIN
    networks:
      - internal

  nginx-proxy:
    image: nginxproxy/nginx-proxy:${NGINX_PROXY_TAG}
    depends_on:
      - nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    tty: true
    volumes:
      - ./nginx-proxy/nginx.conf:${NGINX_CONF}
      - ./nginx-proxy/cors.conf:${NGINX_PROXY_CORS_CONF}
      - certs:${NGINX_CERTS}:ro
      - vhost:${NGINX_VHOST}
      - html:${NGINX_HTML}
      - ${DOCKER_SOCK}:${TEMP_DOCKER_SOCK}:ro
    environment:
      - TRUST_DOWNSTREAM_PROXY
      - CORS_ALLOWED_DOMAIN
    networks:
      - internal

  # letsencrypt:
  #   image: nginxproxy/acme-companion:${ACME_COMPANION_TAG}
  #   depends_on:
  #     - nginx-proxy
  #   restart: unless-stopped
  #   volumes_from:
  #     - nginx-proxy:rw
  #   volumes:
  #     - certs:${NGINX_CERTS}:rw
  #     - acme:${NGINX_ACME}
  #     - ${DOCKER_SOCK}:${DOCKER_SOCK}:ro
  #   environment:
  #     - DEFAULT_EMAIL
  #   networks:
  #     - internal

volumes:
  odoo-data:
  acme:
  certs:
  vhost:
  html:

networks:
  internal:
    driver: bridge
