services:
  odoo:
    restart: 'no'
    ports:
      - 127.0.0.1:8069:8069
      - 127.0.0.1:8070:8070
      - 127.0.0.1:8071:8071
      - 127.0.0.1:8072:8072

  postgres:
    restart: 'no'
    ports:
      - 127.0.0.1:5432:5432

  nginx:
    restart: 'no'

  nginx-proxy:
    restart: 'no'
    ports:
      - 80:80
      - 443:443
