services:
  odoo:
    restart: unless-stopped
    ports:
      - 127.0.0.1:8069:8069
      - 127.0.0.1:8070:8070
      - 127.0.0.1:8071:8071
      - 127.0.0.1:8072:8072

  postgres:
    restart: unless-stopped
    ports:
      - 127.0.0.1:5432:5432

  nginx:
    restart: unless-stopped

  nginx-proxy:
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443

  letsencrypt:
    restart: unless-stopped

  redis:
    restart: unless-stopped

  s3:
    restart: unless-stopped

  pgadmin:
    restart: unless-stopped
