services:
  odoo:
    restart: unless-stopped
    ports:
      - 127.0.0.1:8069:8069
      - 127.0.0.1:8071:8071
      - 127.0.0.1:8072:8072

  postgres:
    restart: unless-stopped
    ports:
      - 127.0.0.1:5432:5432

  nginx-proxy:
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443

volumes:
  acme:
  certs:
