services:
  pgadmin:
    build:
      context: ./
      dockerfile: ./pgadmin/Dockerfile
      args:
        - PGADMIN_TAG
    depends_on:
      - postgres
    restart: 'no'
    expose:
      - 80
    volumes:
      - pgadmin-data:${PGADMIN_DATA}
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
      - VIRTUAL_HOST=${PGADMIN_VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${PGADMIN_LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${PGADMIN_LETSENCRYPT_EMAIL}
      - PGADMIN_CONFIG_APP_NAME
      - PGADMIN_CONFIG_CONFIG_DATABASE_CONNECTION_POOL_SIZE
      - PGADMIN_CONFIG_SERVER_MODE
      - PGADMIN_CONFIG_DEFAULT_SERVER
      - PGADMIN_CONFIG_DEFAULT_SERVER_PORT
      - PGADMIN_CONFIG_PASSWORD_LENGTH_MIN
      - PGADMIN_CONFIG_MAX_SESSION_IDLE_TIME
      - PGADMIN_CONFIG_CONFIG_DATABASE_URI
      - PGADMIN_CONFIG_ALLOW_SAVE_PASSWORD
      - PGADMIN_CONFIG_MAX_QUERY_HIST_STORED
      - PGADMIN_CONFIG_MAIL_SERVER
      - PGADMIN_CONFIG_MAIL_PORT
      - PGADMIN_CONFIG_MAIL_USE_SSL
      - PGADMIN_CONFIG_MAIL_USE_TLS
      - PGADMIN_CONFIG_MAIL_USERNAME
      - PGADMIN_CONFIG_MAIL_PASSWORD
      - PGADMIN_CONFIG_MAIL_DEBUG
      - PGADMIN_CONFIG_SECURITY_EMAIL_SENDER
      - PGADMIN_CONFIG_ALLOW_SAVE_TUNNEL_PASSWORD
      - PGADMIN_CONFIG_MAX_LOGIN_ATTEMPTS
    networks:
      - internal

volumes:
  pgadmin-data:
