services:
  odoo:
    restart: unless-stopped
    ports:
      - 127.0.0.1:8069:8069
      - 127.0.0.1:8070:8070
      - 127.0.0.1:8071:8071
      - 127.0.0.1:8072:8072

  postgres:
    restart: unless-stopped
    ports:
      - 127.0.0.1:5432:5432

  pgbouncer:
    restart: unless-stopped
    expose:
      - 5432/tcp

  nginx:
    restart: unless-stopped

  nginx-proxy:
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443

  traefik: 
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    command:
      - --entrypoints.websecure.address=${ENTRYPOINTS_WEBSECURE_ADDRESS}
      - --certificatesresolvers.leresolver.acme.httpchallenge=${ACME_HTTPCHALLENGE}
      - --certificatesresolvers.leresolver.acme.httpchallenge.entrypoint=${ACME_HTTPCHALLENGE_ENTRYPOINT}
      - --certificatesresolvers.leresolver.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.leresolver.acme.storage=${ACME_STORAGE}
      - --certificatesresolvers.leresolver.acme.caserver=${ACME_CASERVER}
    labels:
      - traefik.http.routers.http-catchall.middlewares=${HTTP_CATCHALL_MIDDLEWARES}
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=${MIDDLEWARES_REDIRECT_SCHEME}
      - traefik.http.routers.traefik-dashboard.entrypoints=${TRAEFIK_DASHBOARD_ENTRYPOINTS}
      - traefik.http.routers.traefik-dashboard.tls.certresolver=${TRAEFIK_DASHBOARD_TLS_CERTRESOLVER}

  acme-companion:
    restart: unless-stopped

  keydb:
    restart: unless-stopped

  minio:
    restart: unless-stopped

  pgadmin:
    restart: unless-stopped
