version: '3'

services:
  odoo:
    ports:
      - "8069:8069"
      - "8070:8070"
      - "8071:8071"
      - "8072:8072"

  postgres:
    ports:
      - "5432:5432"

  nginx:
    restart: unless-stopped

  nginx-proxy:
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
